[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]

[tool.black]
line-length = 99
target-version = ['py310']
skip-string-normalization = true

[tool.isort]
profile = 'black'

[tool.setuptools_scm]
version_scheme = 'post-release'
