[build-system]
requires = ["setuptools>=45", "wheel", "versioneer[toml]"]
build-backend = "setuptools.build_meta"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "migas_server/_version.py"
versionfile_build = "migas_server/_version.py"
tag_prefix = ""
parentdir_prefix = ""

[tool.black]
line-length = 99
target-version = ['py310']
skip-string-normalization = true
exclude = ["migas_server/_version.py"]

[tool.isort]
profile = 'black'
skip = ["migas_server/_version.py"]
