[build-system]
requires = ["flit_scm"]
build-backend = "flit_scm:buildapi"

[project]
name = "migas-server"
description = "Migas telemetry server"
readme = "README.md"
license = {file = "LICENSE"}
maintainers = [
    {name = "Nipreps developers", email = "nipreps@gmail.com"},
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">3.10"
dependencies = [
    "aiohttp",
    "redis >=4.2.0",
    "asyncpg",
    "fastapi[all]",
    "packaging",
    "strawberry-graphql[fastapi]",
    "sqlalchemy[async]",
]
dynamic = ["version"]

[project.optional-dependencies]
heroku = [
    "alembic",
    "scout-apm",
]
speedups = [
    "aiohttp[speedups]",
    "redis[hiredis]",
]
dev = [
    "black",
    "isort",
    "pre-commit",
]
test = [
    "pytest",
]

[project.scripts]
migas-server = "migas_server.cli:main"

[tool.flit.sdist]
exclude = [".gitignore"]

[tool.setuptools_scm]
write_to = "migas_server/_version.py"

[tool.black]
line-length = 99
target-version = ['py310']
skip-string-normalization = true

[tool.isort]
profile = 'black'
