steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/migas-server:$TAG_NAME',
        '--build-arg', 'BUILDTYPE=release',
        '--build-arg', 'VERSION=$TAG_NAME',
        '.']

options:
  logging: CLOUD_LOGGING_ONLY

images:
- 'gcr.io/$PROJECT_ID/migas-server:$TAG_NAME'
