steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/migas-server:$TAG_NAME', '--build-arg', 'BUILDTYPE=release', '.']

images:
- 'gcr.io/$PROJECT_ID/migas-server:$TAG_NAME'
