name: Deploy tag to production and create GH release

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Authenticate and setup SDK
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/783007238857/locations/global/workloadIdentityPools/migas-gha/providers/github-actions'
          service_account: 'gh-actions@migas-362318.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      # Use provided deployment script
      - name: Run deployment script
        run: ./deploy/gcp/release-gcp.sh ${{ github.ref }}

  release:
    runs-on: ubuntu-latest
    needs: deploy
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Create GitHub release from annotated tag
        uses: spenserblack/actions-tag-to-release@v1.1.0
        with:
          prerelease: auto
          prerelease-pattern: '*rc*'
