name: Deploy current master to staging app

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: Install builds buildpack
        run: heroku plugins:install heroku-builds
      - name: Install python build
        run: python -m pip install build
      - name: Package app
        run: python -m build --sdist
      - name: Pass in built app to Heroku deployment
        run: |
          SOURCE=$(ls dist/migas_server*.tar.gz)
          heroku builds:create -a migas --source-tar=$SOURCE
        env:
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
