name: Authenticate through GCP and if tagged, deploy to production + publish GH release

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Authenticate and setup SDK
      - id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          token_format: 'access_token'
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Get gcloud information
        run: gcloud info
      # Cloud Build + Cloud Run
      - name: Extract tag name
        id: tagname
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - name: Submit to Cloud Build
        id: cloudbuild
        run: |
          TAG=${{ steps.tagname.outputs.TAG_NAME }}
          GCR_TAG="gcr.io/$PROJECT_ID/$CLOUD_RUN_SERVICE_NAME:$TAG"
          gcloud builds submit --config deploy/gcp/cloudbuild.yml --substitutions=TAG_NAME=$TAG
          echo ::set-output name=GCR_TAG::${GCR_TAG}
      - name: Create environment file for Cloud Run
        run: echo ${{ secrets.CLOUD_RUN_ENV_FILE }} > .env
      - name: Deploy to Cloud Run
        id: cloudrun
        run: |
          GCR_TAG=${{ steps.cloudbuild.outputs.GCR_TAG}}
          gcloud run deploy migas-server \
            --region=us-central1 \
            --image=$GCR_TAG \
            --platform=managed \
            --min-instances=1 \
            --max-instances=3 \
            --ingress=all \
            --allow-unauthenticated \
            --set-cloudsql-instances=${{ secrets.SQL_INSTANCE_NAME }} \
            --memory=512Mi \
            --cpu=2 \
            --args=--host,0.0.0.0,--port,8080,--proxy-headers,--header,X-Backend-Server:migas \
            --cpu-throttling \
            --env-vars-file=.env

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: deploy
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Create GitHub release from annotated tag
        uses: spenserblack/actions-tag-to-release@v1.1.0
        with:
          prerelease: auto
          prerelease-pattern: '*rc*'
